[workspace]
members = [
    "crates/prooflab",
    "crates/prooflab_io",
    "examples/bubble_sort",
    "examples/ecdsa",
    "examples/eddsa",
    "examples/fibonacci",
    "examples/is_even",
    "examples/json",
    "examples/keccak256",
    "examples/regex",
    "examples/rsa",
    "examples/sha",
    "examples/tendermint",
    "examples/zkquiz",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"