[package]
name = "helios_light_client"
version = "0.1.0"
edition = "2021"

[dependencies]
prooflab_io = { git = "https://github.com/prooflabdev/prooflab-rs.git", package = "prooflab_io" }
helios_light_client_lib = { path = "./lib" }
helios-consensus-core = { git = "https://github.com/a16z/helios", version = "0.7.0", rev="f2a90baa192feb14de1a470882eb5a79bf805043" }
alloy-primitives = { version = "0.8.22", features = ["serde"] }
ssz-rs = { package = "ssz_rs", version = "0.9.0" }
tree_hash = "0.9.1"
serde = "1.0.203"
serde_cbor = "0.11.2"

[patch.crates-io]
ethereum_hashing = { git = "https://github.com/ncitron/ethereum_hashing", rev = "7ee70944ed4fabe301551da8c447e4f4ae5e6c35" }